[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Research"
  pageRef = "research"
  weight = 12

[[main]]
  name = "News"
  pageRef = "news"
  weight = 15

[[main]]
  name = "Writing"
  pageRef = "blogs"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "Research"
  pageRef = "research"
  weight = 12

[[footer]]
  name = "News"
  pageRef = "news"
  weight = 15

[[footer]]
  name = "Writing"
  pageRef = "blogs"
  weight = 20

[[footer]]
  name = "RSS"
  pre = "rss"
  url = "/blogs/index.xml"
  weight = 40

[[footer]]
  name = "Projects"
  pageRef = "projects"
  weight = 30
