[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/Methaphur"
  weight = 90

[[main]]
  identifier = "email"
  pre = "envelope"
  url = "mailto:harisankar.b@niser.ac.in"
  weight = 100

[[main]]
  identifier = "linkedin"
  pre = "linkedin"
  url = "https://in.linkedin.com/in/harisankar-binod"
  weight = 101

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "Blogs"
  pageRef = "blogs"
  weight = 20

[[footer]]
  name = "Projects"
  pageRef = "projects"
  weight = 30

[[footer]]
  name = "RSS"
  pre = "rss"
  url = "/blogs/index.xml"
  weight = 25